/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["healthz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["readyz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["version"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["updateMe"];
    trace?: never;
  };
  "/users/me/preferences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPreferences"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["updatePreferences"];
    trace?: never;
  };
  "/users/me/notifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Caller's explicit notification modes. rows with room_id "" are the default; others are room overrides (docs/REQUIREMENTS.md). */
    get: operations["listNotificationModes"];
    put?: never;
    post: operations["setNotificationMode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["changePassword"];
    trace?: never;
  };
  "/users/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["searchUsers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: components["parameters"]["UserId"];
      };
      cookie?: never;
    };
    get: operations["getUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/contacts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listContacts"];
    put?: never;
    post: operations["addContact"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/contacts/{contactId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contactId: components["parameters"]["ContactId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["removeContact"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rooms": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listRooms"];
    put?: never;
    post: operations["createRoom"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rooms/{roomId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    get: operations["getRoom"];
    put?: never;
    post?: never;
    /** @description Soft-deletes the room (room admins; the creator of a group_direct room is its admin). The room and its history remain in the database but every member's room list omits it, and subscribers receive a room.archived event (docs/WEBSOCKETS.md). Member-level archive lives on the client via PUT /rooms/{roomId}/archived. */
    delete: operations["archiveRoom"];
    options?: never;
    head?: never;
    patch: operations["updateRoom"];
    trace?: never;
  };
  "/rooms/{roomId}/pin": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    get?: never;
    put: operations["pinMessage"];
    post?: never;
    delete: operations["unpinMessage"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rooms/{roomId}/members": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    get: operations["listRoomMembers"];
    put?: never;
    post: operations["addRoomMember"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rooms/{roomId}/members/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
        userId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["removeRoomMember"];
    options?: never;
    head?: never;
    /** @description Promote or demote a member (room admins and server admins). The last admin of a room cannot be demoted (409 conflict). Emits room.member_role_changed. */
    patch: operations["setRoomMemberRole"];
    trace?: never;
  };
  "/rooms/{roomId}/archived": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    get?: never;
    /** @description Per-member conversation archive (web client's archived view, docs/CLIENT_WEB.md). Distinct from the admin room-level archive (`DELETE /rooms/{roomId}`). */
    put: operations["setMemberArchive"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rooms/{roomId}/read": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["markRead"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/invites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listMyInvites"];
    put?: never;
    post: operations["createInvite"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/invites/{inviteId}/accept": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        inviteId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["acceptInvite"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/invites/{inviteId}/decline": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        inviteId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["declineInvite"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/invites/{inviteId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        inviteId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Decline alias on request methods the clients use. */
    delete: operations["removeInvite"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/attachments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createUploadSession"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/attachments/{attachmentId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        attachmentId: components["parameters"]["AttachmentId"];
      };
      cookie?: never;
    };
    get: operations["getAttachment"];
    put?: never;
    post?: never;
    delete: operations["deleteAttachment"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/attachments/{attachmentId}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        attachmentId: components["parameters"]["AttachmentId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["completeUpload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rooms/{roomId}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    get: operations["listMessages"];
    put?: never;
    post: operations["createMessage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/messages/{messageId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        messageId: components["parameters"]["MessageId"];
      };
      cookie?: never;
    };
    get: operations["getMessage"];
    put?: never;
    post?: never;
    delete: operations["deleteMessage"];
    options?: never;
    head?: never;
    patch: operations["updateMessage"];
    trace?: never;
  };
  "/messages/{messageId}/reactions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        messageId: components["parameters"]["MessageId"];
      };
      cookie?: never;
    };
    get: operations["listReactions"];
    put?: never;
    post: operations["react"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/messages/{messageId}/reactions/{emoji}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        messageId: components["parameters"]["MessageId"];
        emoji: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["unreact"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/devices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["registerDevice"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/devices/{deviceId}/validate": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        deviceId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["validateDevice"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/devices/{deviceId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        deviceId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteDevice"];
    options?: never;
    head?: never;
    /** @description Replace the device's push registration (endpoint renewal). */
    patch: operations["renewDevice"];
    trace?: never;
  };
  "/push/vapid": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description RFC 8292 public key for connector registration (base64url, 87 bytes). */
    get: operations["getVapidPublicKey"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ws": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description WebSocket (docs/WEBSOCKETS.md) — same-origin upgrade, cookie or bearer
     *     auth (ADR-015). Frames: subscribe/unsubscribe, typing.started/stopped,
     *     ack, read; server events per the envelope list there. Not a REST
     *     resource; listed for contract completeness.
     */
    get: operations["wsEndpoint"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      error: components["schemas"]["ErrorBody"];
    };
    ErrorBody: {
      /** @description Stable machine-readable error code. */
      code: string;
      /** @description Human-readable message. */
      message: string;
    };
    ChangePasswordRequest: {
      /** Format: password */
      old_password: string;
      /** Format: password */
      new_password: string;
    };
    LoginRequest: {
      username: string;
      /** Format: password */
      password: string;
      /**
       * @description Non-browser clients (Android, integrations) set this to receive the opaque session token in the response body for `Authorization: Bearer` use; browser clients use the cookie only (ADR-015).
       * @default false
       */
      token_request: boolean;
    };
    /** @description Login response. Browsers: cookie set, `token` omitted. Clients that sent `token_request: true` receive the opaque session token for bearer use (ADR-015). */
    AuthResponse: {
      /** @description The same opaque session token carried by the cookie; present only when the request set token_request. */
      token?: string;
      user: components["schemas"]["User"];
    };
    User: {
      id: string;
      username: string;
      display_name: string;
      /** @enum {string} */
      role: "user" | "moderator" | "admin";
      /** @description Present only on self payloads (GET/PATCH /users/me, login). */
      email?: string | null;
      /** @description IANA tz name for client-side rendering; UTC RFC 3339 on the wire. */
      timezone?: string | null;
      /** @description Resolved avatar URL (presigned attachment URL, or server-side Gravatar fallback, or null for client-side monogram) — ADR-011. */
      avatar_url: string | null;
      /**
       * Format: date-time
       * @description Null unless the target user's lastSeen preference allows, ADR-013.
       */
      last_seen_at?: string | null;
    };
    UpdateUserRequest: {
      display_name?: string;
      email?: string | null;
      /** @description Set from an attachment created via the upload flow (ADR-011). */
      avatar_attachment_id?: string | null;
    };
    Preferences: {
      last_seen_visible: boolean;
      read_receipts: boolean;
      allow_group_invites: boolean;
      allow_private_messages: boolean;
    };
    /** @description Partial update; omitted fields keep current values. */
    UpdatePreferencesRequest: {
      last_seen_visible?: boolean;
      read_receipts?: boolean;
      allow_group_invites?: boolean;
      allow_private_messages?: boolean;
    };
    AddContactRequest: {
      user_id: string;
    };
    NotificationMode: {
      /** @description Room id for overrides; "" for the user default row. */
      room_id: string;
      /** @enum {string} */
      mode: "all" | "mentions" | "directs" | "never";
    };
    Reaction: {
      emoji: string;
      count: number;
    };
    ReactRequest: {
      emoji: string;
    };
    SetNotificationModeRequest: {
      /** @description Omitted/null sets the user default row; a room id sets that room's override. */
      room_id?: string | null;
      /** @enum {string} */
      mode: "all" | "mentions" | "directs" | "never";
    };
    Contact: {
      id: string;
      user: components["schemas"]["User"];
      /** Format: date-time */
      created_at: string;
    };
    Room: {
      id: string;
      /** @enum {string} */
      type: "public" | "private" | "direct" | "group_direct";
      name?: string | null;
      description?: string | null;
      avatar_url: string | null;
      pinned_message_id?: string | null;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      /** @description Caller's member-level conversation archive flag (sidebar filter). False when the room is returned without membership context. */
      archived?: boolean;
      /**
       * @description Caller's role; present when the caller is a member.
       * @enum {string}
       */
      my_role?: "member" | "admin";
      /** @description Unread (un-read receipts) for the caller; present on room lists. */
      unread_count?: number;
    };
    CreateRoomRequest: {
      /**
       * @description public/private rooms get a name; direct takes exactly one co-member in `members` (contact or allow_private_messages); group_direct takes ≥1 co-members (creator becomes admin).
       * @enum {string}
       */
      type: "public" | "private" | "direct" | "group_direct";
      name?: string | null;
      description?: string;
      /** @description Co-member user ids for direct/group_direct rooms. */
      members?: string[];
    };
    UpdateRoomRequest: {
      name?: string | null;
      description?: string;
      avatar_attachment_id?: string | null;
    };
    PinRequest: {
      message_id: string;
    };
    MemberArchiveRequest: {
      archived: boolean;
    };
    CreateMessageRequest: {
      body: string;
      /**
       * @default markdown
       * @enum {string}
       */
      format: "markdown";
      reply_to_message_id?: string | null;
      attachment_ids?: string[];
    };
    UpdateMessageRequest: {
      body: string;
      /**
       * @default markdown
       * @enum {string}
       */
      format: "markdown";
    };
    Message: {
      id: string;
      room_id: string;
      author_id: string;
      /** @description Hydrated author user payload; present when messages are returned through room/message reads. */
      author?: components["schemas"]["User"];
      body: string;
      format: string;
      reply_to_message_id?: string | null;
      attachments?: components["schemas"]["Attachment"][];
      receipts?: components["schemas"]["Receipts"];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      edited_at?: string | null;
      /**
       * Format: date-time
       * @description Present but non-null only to tombstone deleted messages; deleted bodies are not returned.
       */
      deleted_at?: string | null;
    };
    /** @description Per-message delivery/read state (ADR-009). Senders see state for their own messages; recipients see their own receipts. Omitted when not visible to the caller. */
    Receipts: {
      /** Format: date-time */
      delivered_at?: string | null;
      /** Format: date-time */
      read_at?: string | null;
    };
    MessagePage: {
      items: components["schemas"]["Message"][];
      next_cursor?: string | null;
    };
    Attachment: {
      id: string;
      filename: string;
      mime_type: string;
      /** Format: int64 */
      size_bytes: number;
      /** @description Presigned download URL; may be null when unauthenticated or expired. */
      url?: string | null;
      thumbnail_url?: string | null;
      width?: number | null;
      height?: number | null;
    };
    RegisterDeviceRequest: {
      /** @enum {string} */
      platform: "android" | "web";
      client_name: string;
      client_version?: string;
      push_registration?: components["schemas"]["PushRegistration"];
    };
    PushRegistration: {
      endpoint: string;
      public_key: string;
      auth_secret: string;
    };
    RegisterDeviceResponse: {
      device_id: string;
      /** @description True when a push registration needs the validation ping round trip (docs/UNIFIEDPUSH.md §3.3); the client answers via /devices/{id}/validate. */
      validation_required: boolean;
    };
    ValidateDeviceRequest: {
      /** @description The decrypted validation ping token sent back by the app. */
      token: string;
    };
    /** @description A member's public profile plus their role in this room. */
    RoomMember: components["schemas"]["User"] & {
      /** @enum {string} */
      room_role: "admin" | "member";
    };
    SetMemberRoleRequest: {
      /** @enum {string} */
      role: "admin" | "member";
    };
    AddMemberRequest: {
      user_id: string;
    };
    CreateInviteRequest: {
      room_id: string;
      user_id: string;
      /** Format: date-time */
      expires_at?: string | null;
    };
    Invite: {
      id: string;
      room: components["schemas"]["Room"];
      inviter?: components["schemas"]["User"];
      invitee?: components["schemas"]["User"];
      /** @enum {string} */
      status: "pending" | "accepted" | "declined" | "revoked";
      /** Format: date-time */
      expires_at?: string | null;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      accepted_at?: string | null;
    };
    CreateUploadRequest: {
      filename: string;
      mime_type: string;
      /** Format: int64 */
      size_bytes: number;
      /** @description Optional client checksum, verified at complete. */
      sha256?: string;
    };
    UploadSession: {
      attachment: components["schemas"]["Attachment"];
      /** @description Presigned PUT target; the client uploads directly. */
      upload_url: string;
    };
  };
  responses: {
    /** @description Invalid request */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Unauthorized */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Forbidden — not permitted for this acting user */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    RoomId: string;
    MessageId: string;
    UserId: string;
    ContactId: string;
    AttachmentId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  readyz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ready */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not ready */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  version: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server version */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            version: string;
          };
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Authenticated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logged out */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            status?: string;
          };
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  updateMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRequest"];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  getPreferences: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current preferences */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Preferences"];
        };
      };
    };
  };
  updatePreferences: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePreferencesRequest"];
      };
    };
    responses: {
      /** @description Updated preferences */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Preferences"];
        };
      };
    };
  };
  listNotificationModes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notification modes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotificationMode"][];
        };
      };
    };
  };
  setNotificationMode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetNotificationModeRequest"];
      };
    };
    responses: {
      /** @description Mode stored */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Password changed; all sessions (including this one) revoked. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
    };
  };
  searchUsers: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Matching users (public profiles only) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"][];
        };
      };
    };
  };
  getUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: components["parameters"]["UserId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  listContacts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Contacts (the caller's list) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Contact"][];
        };
      };
    };
  };
  addContact: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddContactRequest"];
      };
    };
    responses: {
      /** @description Added */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Contact"];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  removeContact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        contactId: components["parameters"]["ContactId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listRooms: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Rooms */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Room"][];
        };
      };
    };
  };
  createRoom: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRoomRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Room"];
        };
      };
    };
  };
  getRoom: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Room */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Room"];
        };
      };
    };
  };
  archiveRoom: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Archived */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: components["responses"]["Forbidden"];
    };
  };
  updateRoom: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateRoomRequest"];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Room"];
        };
      };
      403: components["responses"]["Forbidden"];
    };
  };
  pinMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PinRequest"];
      };
    };
    responses: {
      /** @description Pinned */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: components["responses"]["Forbidden"];
    };
  };
  unpinMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Unpinned */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: components["responses"]["Forbidden"];
    };
  };
  listRoomMembers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Members (prefs-gated public profiles) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RoomMember"][];
        };
      };
    };
  };
  addRoomMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddMemberRequest"];
      };
    };
    responses: {
      /** @description Added */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: components["responses"]["Forbidden"];
    };
  };
  removeRoomMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  setRoomMemberRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetMemberRoleRequest"];
      };
    };
    responses: {
      /** @description Updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: components["responses"]["Forbidden"];
      /** @description Would leave the room without an admin */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  setMemberArchive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberArchiveRequest"];
      };
    };
    responses: {
      /** @description Updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  markRead: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PinRequest"];
      };
    };
    responses: {
      /** @description Read advanced */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listMyInvites: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Open invites for the caller */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Invite"][];
        };
      };
    };
  };
  createInvite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateInviteRequest"];
      };
    };
    responses: {
      /** @description Invite created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            invite_id: string;
          };
        };
      };
    };
  };
  acceptInvite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        inviteId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  declineInvite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        inviteId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Declined */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  removeInvite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        inviteId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Declined */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createUploadSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUploadRequest"];
      };
    };
    responses: {
      /** @description Pending attachment + presigned upload URL */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadSession"];
        };
      };
    };
  };
  getAttachment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        attachmentId: components["parameters"]["AttachmentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Attachment with presigned download URL (read-authz, docs/UNIFIEDPUSH.md-adjacent) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Attachment"];
        };
      };
      403: components["responses"]["Forbidden"];
    };
  };
  deleteAttachment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        attachmentId: components["parameters"]["AttachmentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Soft-deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  completeUpload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        attachmentId: components["parameters"]["AttachmentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Attachment verified ready */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Attachment"];
        };
      };
      /** @description Object absent or size/sha mismatch */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listMessages: {
    parameters: {
      query?: {
        limit?: number;
        before?: string;
      };
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Messages */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessagePage"];
        };
      };
    };
  };
  createMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        roomId: components["parameters"]["RoomId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMessageRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Message"];
        };
      };
    };
  };
  getMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        messageId: components["parameters"]["MessageId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Message */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Message"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  deleteMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        messageId: components["parameters"]["MessageId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted (tombstone returned) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Message"];
        };
      };
    };
  };
  updateMessage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        messageId: components["parameters"]["MessageId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMessageRequest"];
      };
    };
    responses: {
      /** @description Updated message */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Message"];
        };
      };
    };
  };
  listReactions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        messageId: components["parameters"]["MessageId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Aggregated reaction counts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Reaction"][];
        };
      };
    };
  };
  react: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        messageId: components["parameters"]["MessageId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReactRequest"];
      };
    };
    responses: {
      /** @description Added */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  unreact: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        messageId: components["parameters"]["MessageId"];
        emoji: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components["responses"]["NotFound"];
    };
  };
  registerDevice: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterDeviceRequest"];
      };
    };
    responses: {
      /** @description Registered */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegisterDeviceResponse"];
        };
      };
    };
  };
  validateDevice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        deviceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ValidateDeviceRequest"];
      };
    };
    responses: {
      /** @description Validation ping round trip complete (docs/UNIFIEDPUSH.md §3.3) */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: components["responses"]["Forbidden"];
    };
  };
  deleteDevice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        deviceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  renewDevice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        deviceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PushRegistration"];
      };
    };
    responses: {
      /** @description Renewed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getVapidPublicKey: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Public key */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            public_key: string;
          };
        };
      };
    };
  };
  wsEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: never;
  };
}
